//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_order
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> order_id { get; set; }
        public string product { get; set; }
        public Nullable<int> price { get; set; }
        public string note { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public string image { get; set; }
    
        public virtual order order { get; set; }
    }
}
